model_checkpoint = "bert-base-cased"
MODEL_PUBMEBERT = "microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract-fulltext"
MODEL_SCIBERT = "allenai/scibert_scivocab_cased"
MODEL_BIOBERT = "dmis-lab/biobert-base-cased-v1.1"
FILE_NAME = "D:\BioNLP\BIONER_ER\datas\BC4CHEMD"